version: "3.3"
services:
  ied1_xcbr:
    build:
      context: .
      dockerfile: Dockerfile.libiec61850_server
    hostname: IED1_XCBR
    command: "/srv/libiec61850_server eth0 102 /cfg/IED1_XCBR.cfg /cfg/IED1_XCBR.ext R 65000"
    volumes:
      - ./cfg:/cfg
    networks:
      subnetwork1:
        ipv4_address: 10.0.0.2
    privileged: true

  ied2_ptoc:
    build:
      context: .
      dockerfile: Dockerfile.libiec61850_server
    hostname: IED2_PTOC
    command: "/srv/libiec61850_server eth0 102 /cfg/IED2_PTOC.cfg /cfg/IED2_PTOC.ext R 65000"
    volumes:
      - ./cfg:/cfg
    networks:
      subnetwork1:
        ipv4_address: 10.0.0.3
    privileged: true

  ied3_smv:
    build:
      context: .
      dockerfile: Dockerfile.libiec61850_server
    hostname: IED3_SMV
    command: "/srv/libiec61850_server eth0 102 /cfg/IED3_SMV.cfg /cfg/IED3_SMV.ext R 65000"
    volumes:
      - ./cfg:/cfg
    networks:
      subnetwork1:
        ipv4_address: 10.0.0.4
    privileged: true

  ied4_smv:
    build:
      context: .
      dockerfile: Dockerfile.libiec61850_server
    hostname: IED4_SMV
    command: "/srv/libiec61850_server eth0 102 /cfg/IED4_SMV.cfg /cfg/IED4_SMV.ext R 65000"
    volumes:
      - ./cfg:/cfg
    networks:
      subnetwork1:
        ipv4_address: 10.0.0.5
    privileged: true

networks:
  subnetwork1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
