services:
  simulator:
    image: ghcr.io/passific/circuit_simulator:latest
    hostname: simulator
    volumes:
      - ./scd:/srv/scd
    networks:
      subnetwork1:
        ipv4_address: 10.0.0.254
#    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "5010:5010"

  client:
    image: ghcr.io/passific/libiec61850_client:latest
    hostname: client
    networks:
      subnetwork1:
        ipv4_address: 10.0.0.11
#    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "5000:5000"
